### ISSUE TITLE
Line breaks in Hamlet

### ISSUE THREAD

**Issue by pharpend** [yesodweb/shakespeare#150] opened 2015-02-06 01:05 UTC
I have this Hamlet code at the footer of my `default-layout-wrapper.hamlet` file:

```html
      <footer>
        <p>
          Copyright © 2015 Peter Harpending
        <p>
          Snotra's <a href="https://gitlab.com/pharpend/snotra">source
          code</a> is freely available under the <a
          href="https://gnu.org/licenses/agpl.html">GNU Affero General
          Public License, version 3 or later</a>.
```

The line breaks in the middle of the `<p>` tag should translate into `&nbsp;` characters, as they would in normal html. Instead, Yesod is doing this:

![](https://i.imgur.com/GKZ2ObX.png)

Notice that there is just no space inbetween broken lines. Additionally the `<a href=...` is being mistranslated into `<ahref=...`. Here's the generated html:

```html
<footer><p>Copyright © 2015 Peter Harpending</p><p>Snotra's <a href="https://gitlab.com/pharpend/snotra">sourcecode</a> is freely available under the <ahref="https://gnu.org/licenses/agpl.html">GNU Affero GeneralPublic License, version 3 or later</a>.</p></footer>
```

**Comment by snoyberg** [comment] 2015-02-08 08:06
I just tested this on my system, and I didn't see the same output as you. Instead, the generated HTML I saw was:

```html
<footer><p>Copyright © 2015 Peter Harpending</p>
<p>Snotra's <a href="https://gitlab.com/pharpend/snotra">source
code</a> is freely available under the <a
href="https://gnu.org/licenses/agpl.html">GNU Affero General
Public License, version 3 or later</a>.</p>
</footer>
```

Perhaps you have some other flag in use?

**Comment by MaxGabriel** [comment] 2015-02-08 08:42
I can reproduce if I just replace the `<footer>` tag from the scaffolding with @pharpend's footer, [like this](https://github.com/MaxGabriel/LineBreakIssue/blob/242726f72b14f4f61df48ef2636f8c2ffb18a9d1/templates/default-layout-wrapper.hamlet#L30-L37).

![image](https://cloud.githubusercontent.com/assets/1274145/6095925/aadd8ce0-af29-11e4-841a-81aa45a7b95c.png)

```html
<footer><p>Copyright © 2015 Peter Harpending</p><p>Snotra's <a href="https://gitlab.com/pharpend/snotra">sourcecode</a> is freely available under the <ahref="https://gnu.org/licenses/agpl.html">GNU Affero GeneralPublic License, version 3 or later</a>.</p></footer>
```

<hr>

I haven't investigated much into why, but I can't reproduce with a simple script (this one is from the Yesod book, but with the HTML changed):

```haskell
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE OverloadedStrings #-}
import Text.Hamlet (HtmlUrl, hamlet)
import Text.Blaze.Html.Renderer.String (renderHtml)
import Data.Text (Text)

data MyRoute = Home

render :: MyRoute -> [(Text, Text)] -> Text
render Home _ = "/home"

main :: IO ()
main = putStrLn $ renderHtml $ [hamlet|
<footer>
  <p>
    Copyright © 2015 Peter Harpending
  <p>
    Snotra's <a href="https://gitlab.com/pharpend/snotra">source
    code</a> is freely available under the <a
    href="https://gnu.org/licenses/agpl.html">GNU Affero General
    Public License, version 3 or later</a>.
|] render
```

**Comment by snoyberg** [comment] 2015-02-08 08:52
That file starts with `$newline never`. With that setting turned on, this is the expected behavior. Removing that line should give the behavior I demonstrated.

Perhaps we should consider modifying the scaffolding to stop using `$newline never`.

Thanks for looking into this Max.

**Comment by MaxGabriel** [comment] 2015-02-08 17:04
Oh so *that's* what `$newline never` does. I didn't actually know what that was doing

**Comment by wolftune** [comment] 2015-05-10 23:22
What are the advantages to `$newline never`?

Is it mainly so that we smoosh together into one line things like the following?

```
<p>
  blah blah
  <em>or
  yadda yadda
 <strong>but not
  ho hum.
```

(In that example, the hamlet approach of avoiding closing tags is nice, but the line-splits make less reasonable sense in rendered HTML, though still would be okay…)

Having read this issue discussion, I'm inclined to maybe avoid `$newline never`, and wondering if there's a good reason to stick with it… I would assume it perfectly reasonable to add `$newline never` in-place wherever I knew I wanted it…

**Comment by snoyberg** [comment] 2015-07-19 21:51
That's certainly acceptable.

I'm closing this issue, as it appears shakespeare is working as designed.

**Closed by snoyberg** 2015-07-19 21:51 UTC
